=== chordflower/riconto/api/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "config",
  "description": "This is the schema of a configuration file for riconto",
  "type": "object",
  "additionalItems": true,
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the project",
      "minLength": 1
    },
    "version": {
      "type": "string",
      "description": "The project version",
      "default": "0.0.1"
    },
    "description": {
      "type": "string",
      "description": "The project description",
      "default": ""
    },
    "license": {
      "type": "array",
      "description": "The project license(s) in spdx format",
      "additionalItems": false,
      "items": {
        "type": "string"
      }
    },
    "files": {
      "type": "array",
      "description": "A list of root files to build",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "path",
          "output"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "A name to identify the output file",
            "examples": [
              "Book A"
            ],
            "minLength": 1
          },
          "output": {
            "type": "string",
            "description": "The name of the output file without extension (it will suffixed)",
            "examples": [
              "./dist/bookA"
            ],
            "minLength": 1
          },
          "path": {
            "type": "string",
            "description": "The path of the main markdown file",
            "examples": [
              "./dist/main.md"
            ],
            "minLength": 1
          }
        }
      }
    },
    "authors": {
      "type": "array",
      "description": "The project author(s)",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The author name"
          },
          "url": {
            "type": "string",
            "format": "iri-reference",
            "description": "The author site"
          },
          "email": {
            "type": "string",
            "format": "idn-email",
            "description": "The user email"
          }
        }
      }
    }
  }
}

=== chordflower/riconto/api/config.json
{
  "$schema": "./config.schema.json",
  "name": "sample",
  "version": "0.0.1",
  "description": "Some description",
  "authors": [
    {
      "name": "carddamom",
      "url": "https://github.com/carddamom",
      "email": "carddamom@tutanota.com"
    }
  ],
  "files": [
    {
      "name": "Book A",
      "output": "./dist/bookA",
      "path": "./src/bookA/main.md"
    },
    {
      "name": "Book B",
      "output": "./dist/bookB",
      "path": "./src/bookB/main.md"
    }
  ],
  "license": [
    "GPL-3.0-or-later"
  ]
}
